# This is a basic workflow to help you get started with Actions

name: Python pipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "python_impl" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build docker testing image
        run: |
          echo $CR_PAT | docker login ghcr.io -u alfberdi --password-stdin
          docker build -t drunk-testing .
          docker build -t drunk --target drunk .
          docker push drunk-testing
          docker push drunk

  flake8:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Login to ghcr
        run: echo $CR_PAT | docker login ghcr.io -u alfberdi --password-stdin

      - name: Run flake8
        run: docker run drunk-testing flake8 drunk tests

  pylint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Login to ghcr
        run: echo $CR_PAT | docker login ghcr.io -u alfberdi --password-stdin

      - name: Run pylint
        run: docker run drunk-testing pylint drunk tests

  mypy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Login to ghcr
        run: echo $CR_PAT | docker login ghcr.io -u alfberdi --password-stdin

      - name: Run mypy
        run: docker run drunk-testing mypy drunk tests