# This is a basic workflow to help you get started with Actions

name: Python pipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "python_impl" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Build docker testing image
        run: |
          docker build -t ghcr.io/dani-zero-to-hero/drunkgame-backend:testing-latest .
          docker build -t ghcr.io/dani-zero-to-hero/drunkgame-backend:latest --target drunk .
          docker push ghcr.io/dani-zero-to-hero/drunkgame-backend:testing-latest
          docker push ghcr.io/dani-zero-to-hero/drunkgame-backend:latest

  flake8:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Run flake8
        run: docker run ghcr.io/dani-zero-to-hero/drunk-testing flake8 drunk tests

  pylint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Run pylint
        run: docker run ghcr.io/dani-zero-to-hero/drunk-testing pylint drunk tests

  mypy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Run mypy
        run: docker run ghcr.io/dani-zero-to-hero/drunk-testing mypy drunk tests